# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - uses: actions/checkout@v2         # checkout the repo
    - run: mvn clean package
      working-directory: back
      
    - uses: actions/upload-artifact@v2  # upload test results
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: test-results
        path: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
    
    - name: JaCoCo Code Coverage Report
      id: jacoco_reporter
      uses: PavanMudigonda/jacoco-reporter@v4.8
      with:
        coverage_results_path: ${{ github.workspace }}/back/target/site/jacoco/jacoco.xml
        coverage_report_name: Coverage
        coverage_report_title: JaCoCo
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_check_run: false
        minimum_coverage: 80
        fail_below_threshold: false
        publish_only_summary: false
    
    # Publish Coverage Job Summary  # Optional
    - name: Add Coverage Job Summary
      run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY
        
    # uploads the coverage-report.md artifact  # Optional

    - name: Upload Code Coverage Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report-markdown
        path: "*/coverage-results.md"
        retention-days: 1
  
