# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: front/package.json

    - run: npm ci
    - run: npm build
    - run: npm test --watch=false --browsers=ChromeHeadless --code-coverage --reporters=mocha

    - name: Test Report
      uses: phoenix-actions/test-reporting@v8
      id: test-report               # Set ID reference for step
      if: success() || failure()
      with:
        name: JEST Tests            # Name of the check run which will be created
        path:  ${{ github.workspace }}/front/Chrome_Headless_118.0.5993.71_(Windows_10)/test-results.xml    # Path to test results
        reporter: jest-junit        # Format of test results

    - name: Read output variables
      run: |
        echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
  
    
    
