name: 'Test Report'
on:
  workflow_run:
    workflows: ['Java CI with Maven']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        artifact: test-results            # artifact name
        paths: 'jacoco.xml'
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 0
        min-coverage-changed-files: 0
        title: '# :lobster: Coverage Report'
        pass-emoji: ':green_circle:'
        fail-emoji: ':red_circle:'